### ISSUE TITLE
Error when loading Kibana dashboard example

### ISSUE THREAD

**Issue by damageco** [YaSuenag/hsbeat#4]
Hello,

When I try to import the file kibana.json with Kibana 4.4.1, I've got this message "_Could not locate that index-pattern-field (id: long_val)_"

This field doesn't seem to be in the index structure anymore. 

Thanks,

David

**Comment by YaSuenag** [comment]
Thank you for your report!
I've fixed in https://github.com/YaSuenag/hsbeat/commit/0a55bd67bac2e586450504ae94856be29ccad21b .

**Comment by damageco** [comment]
Thanks, but now I've got _Error: Could not locate that index-pattern-field (id: sun/gc/metaspace/capacity)_

I'm using java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by YaSuenag** [comment]
Metaspace is included from Java 8 or later.
I confirmed this dashboard with OpenJDK 8.

If you want to use HSBeat with Java 7, you have to create or change PerfCounter name in Visualization.
