### ISSUE TITLE
Template file need to be updated

### ISSUE THREAD

**Issue by damageco** [YaSuenag/hsbeat#5]
When I PUT the hsbeat-template.json file on a fresh Elasticsearch 2.2.0 the index is pretty empty. Have only got :
_index                    | _type    |   _id                                    |score▼
hsbeat-2016.02.21 | hsbeat | AVMFDdhoBKdyR4fN98Ri | 1

I've already note this before, but it seems to works better without any template file, but I was wrong. All data are imported but values are completely wrong.
It seems that template file need a refresh... :-)

**Comment by damageco** [comment]
I've looked at your changes of the last days. May be it's could be useful to a mode that generate the template mapping...

**Comment by YaSuenag** [comment]
I use [Dynamic Template](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html) in HSBeat because PerfCounters are NOT fixed in each HotSpot VM.

I want to use HSBeat with many version of HotSpot. So I do not create static mapping.

**Comment by damageco** [comment]
Ok, understood. It's seems to work quiet well if I remove mapping with
`curl -XDELETE http://localhost:9200/_template/hsbeat`

Problem just seems to be that term like
"sun/gc/collector/0/lastEntryTime" have very large value 3345640927123850274, so more than the 16 digits of the default [Precision Step](https://www.elastic.co/guide/en/elasticsearch/reference/current/precision-step.html) for long type.
May be for all "*Time" field you could use the division by "sun.os.hrt.frequency", which is only in first results set. It's seems that's the way Sun use it in [JStat](http://hg.openjdk.java.net/jdk7u/jdk7u60/jdk/file/33c1eee28403/src/share/classes/sun/tools/jstat/resources/jstat_options) tool.

**Comment by YaSuenag** [comment]
HSBeat collects all of raw hsperfdata.
Thus I think that we should calculate time value in visualization.

I've added time calculation in Kibana dashboard sample.
Could you try it?

**Comment by damageco** [comment]
Doesn't seems to work in my Kibana/Elasticsearch set.
`Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"script_exception","reason":"failed to run inline script [doc['sun/rt/applicationTime/diff'].value / doc['sun/os/hrt/frequency'].value] using lang [groovy]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"hsbeat-2016.02.23","node":"66PYU36CR1OhIyC6fKdP9A","reason":{"type":"script_exception","reason":"failed to run inline script [doc['sun/rt/applicationTime/diff'].value / doc['sun/os/hrt/frequency'].value] using lang [groovy]","caused_by":{"type":"arithmetic_exception","reason":"Division by zero"}}}]}}
KbnError@http://localhost:5601/bundles/commons.bundle.js?v=9693:57416:21
RequestFailure@http://localhost:5601/bundles/commons.bundle.js?v=9693:57449:1
callResponseHandlers/<@http://localhost:5601/bundles/kibana.bundle.js?v=9693:79004:39
__WEBPACK_AMD_DEFINE_RESULT__</</Promise.try@http://localhost:5601/bundles/commons.bundle.js?v=9693:61111:20
__WEBPACK_AMD_DEFINE_RESULT__</</Promise.map/<@http://localhost:5601/bundles/commons.bundle.js?v=9693:61080:17
__WEBPACK_AMD_DEFINE_RESULT__</</Promise.map@http://localhost:5601/bundles/commons.bundle.js?v=9693:61079:27
callResponseHandlers@http://localhost:5601/bundles/kibana.bundle.js?v=9693:78976:1
fetchWithStrategy/<@http://localhost:5601/bundles/kibana.bundle.js?v=9693:78483:17
processQueue@http://localhost:5601/bundles/commons.bundle.js?v=9693:42357:29
scheduleProcessQueue/<@http://localhost:5601/bundles/commons.bundle.js?v=9693:42373:28
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:5601/bundles/commons.bundle.js?v=9693:43601:17
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:5601/bundles/commons.bundle.js?v=9693:43412:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:5601/bundles/commons.bundle.js?v=9693:43709:14
done@http://localhost:5601/bundles/commons.bundle.js?v=9693:38158:37
completeRequest@http://localhost:5601/bundles/commons.bundle.js?v=9693:38356:8
requestLoaded@http://localhost:5601/bundles/commons.bundle.js?v=9693:38297:1`
I think it's because 'sun/os/hrt/frequency' is only return once at the start of the script, and does not appears in next docs stored in Elasticsearch...

**Comment by YaSuenag** [comment]
What revision did you use?
I guess that you use older revision (https://github.com/YaSuenag/hsbeat/commit/9bc34e98bd59bf441483d63f607cd79881cb407b or earlier)

**Comment by damageco** [comment]
Don't think so. I've updated to last commit. Same results.
Results of command git log

```
# git log
commit 9033ce7459909e84fa1ce42f44c37066925d6bcf
Author: Yasumasa Suenaga <yasuenag@gmail.com>
Date:   Wed Feb 24 12:43:18 2016 +0900

    Remove profiling comments.
```

The last binary asked me to add -p parameter so I think I'm on the _bleeding edge of technology_ ;-)

**Comment by YaSuenag** [comment]
Your binary is correct.
I guess that your documents in ES do not contain sun/os/hrt/frequency field value.
Please check this value if you can.
(e.g. draw line chart with this field in Kibana)

This value is defined in hsbeat.yml (force_collect setting). Could you check hsbeat.yml ? If it is set, please run hsbeat with -c option (choose configuration file)

https://www.elastic.co/guide/en/beats/libbeat/current/command-line-options.html

**Comment by YaSuenag** [comment]
I confirmed that latest HSBeat source works fine as below:
- Environment
  - OS: Fedora23 x86_64
  - ES: 2.1.1
  - Kibana: 4.3.1
  - Go: golang-1.5.3-1.fc23.x86_64
- Refresh $GOPATH

``` bash
$ rm -fR $GOPATH
$ go get github.com/YaSuenag/hsbeat
```
- Start ES and Kibana
- Put index template

``` bash
curl -XPUT http://127.0.0.1:9200/_template/hsbeat -d@$GOPATH/src/github.com/YaSuenag/hsbeat/etc/hsbeat-template.json
```
- Start HSBeat

``` bash
$ $GOPATH/bin/hsbeat -p <PID> -c $GOPATH/src/github.com/YaSuenag/hsbeat/hsbeat.yml
```
- Import `$GOPATH/src/github.com/YaSuenag/hsbeat/etc/kibana.json` to Kibana
- Show dashboard (hsbeat)

**Comment by damageco** [comment]
Find it. I missed the new parameter _force_collect_ in the config file. 

Everything work fine.
Thanks for all.
