### ISSUE TITLE
How to compute heap usage ratio?

### ISSUE THREAD

**Issue by athoune** [YaSuenag/hsbeat#6]
Only java/*\* keys are non-private, but this keys are boring : threads or loading classes. How can I compute heap usage. Something compatible with different java versions.

**Comment by YaSuenag** [comment]
You have to calculate it in your app with sun/gc/generation/*/space/*/capacity and sun/gc/generation/*/space/*/used .
If you want to see heap usage ratio in Kibana, you have to enable dynamic scripting on Elasticsearch and you have to add compute logic to JSON input in Visualization.
(You can see the logic in HSBeat dashboard sample.)

**Comment by YaSuenag** [comment]
I close this issue as question.
If you have any question, please reopen this issue again.
