### ISSUE TITLE
HSBeat can't be built because of dependency problems

### ISSUE THREAD

**Issue by guenhter** [YaSuenag/hsbeat#7]
Hi, when I try to build the project, I get a problem.

This one is documented under
https://discuss.elastic.co/t/hsbeats-compile-error-on-debian/54412

Maybe the dependencies can be changed in this project.

thanks

**Comment by YaSuenag** [comment]
I think this is libbeat problem.
HEAD in beat master branch is for v5.0.0 . It seems not to be compatibility from v1.2 (current release).

We can build HSBeat as below:

```
$ go get github.com/elastic/beats/libbeat
$ cd $GOPATH/src/github.com/elastic/beats
$ git checkout -b v1.2.3 refs/tags/v1.2.3
Switched to a new branch 'v1.2.3'
$ go get github.com/YaSuenag/hsbeat
```

**Comment by guenhter** [comment]
Thanks! This works. I don't think it's very pretty, but who cares; at least it's building now.

**Comment by YaSuenag** [comment]
I pushed Beats v1.2.3 to HSBeat repos.
You do not need to checkout v1.2.3 tag in Beats repos.

I close this issue. Thanks!
